// Code generated by ent, DO NOT EDIT.

package grade

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the grade type in the database.
	Label = "grade"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGradeName holds the string denoting the gradename field in the database.
	FieldGradeName = "grade_name"
	// EdgeStuLogs holds the string denoting the stulogs edge name in mutations.
	EdgeStuLogs = "stuLogs"
	// EdgeClass holds the string denoting the class edge name in mutations.
	EdgeClass = "class"
	// EdgeStudent holds the string denoting the student edge name in mutations.
	EdgeStudent = "student"
	// EdgeDorm holds the string denoting the dorm edge name in mutations.
	EdgeDorm = "dorm"
	// Table holds the table name of the grade in the database.
	Table = "grades"
	// StuLogsTable is the table that holds the stuLogs relation/edge. The primary key declared below.
	StuLogsTable = "stu_log_grade"
	// StuLogsInverseTable is the table name for the StuLog entity.
	// It exists in this package in order to avoid circular dependency with the "stulog" package.
	StuLogsInverseTable = "stu_logs"
	// ClassTable is the table that holds the class relation/edge.
	ClassTable = "classes"
	// ClassInverseTable is the table name for the Class entity.
	// It exists in this package in order to avoid circular dependency with the "class" package.
	ClassInverseTable = "classes"
	// ClassColumn is the table column denoting the class relation/edge.
	ClassColumn = "class_grade"
	// StudentTable is the table that holds the student relation/edge.
	StudentTable = "students"
	// StudentInverseTable is the table name for the Student entity.
	// It exists in this package in order to avoid circular dependency with the "student" package.
	StudentInverseTable = "students"
	// StudentColumn is the table column denoting the student relation/edge.
	StudentColumn = "student_grade"
	// DormTable is the table that holds the dorm relation/edge.
	DormTable = "dorms"
	// DormInverseTable is the table name for the Dorm entity.
	// It exists in this package in order to avoid circular dependency with the "dorm" package.
	DormInverseTable = "dorms"
	// DormColumn is the table column denoting the dorm relation/edge.
	DormColumn = "dorm_grade"
)

// Columns holds all SQL columns for grade fields.
var Columns = []string{
	FieldID,
	FieldGradeName,
}

var (
	// StuLogsPrimaryKey and StuLogsColumn2 are the table columns denoting the
	// primary key for the stuLogs relation (M2M).
	StuLogsPrimaryKey = []string{"stu_log_id", "grade_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Grade queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGradeName orders the results by the gradeName field.
func ByGradeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGradeName, opts...).ToFunc()
}

// ByStuLogsCount orders the results by stuLogs count.
func ByStuLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStuLogsStep(), opts...)
	}
}

// ByStuLogs orders the results by stuLogs terms.
func ByStuLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStuLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByClassCount orders the results by class count.
func ByClassCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClassStep(), opts...)
	}
}

// ByClass orders the results by class terms.
func ByClass(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClassStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStudentCount orders the results by student count.
func ByStudentCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStudentStep(), opts...)
	}
}

// ByStudent orders the results by student terms.
func ByStudent(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStudentStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDormCount orders the results by dorm count.
func ByDormCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDormStep(), opts...)
	}
}

// ByDorm orders the results by dorm terms.
func ByDorm(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDormStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStuLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StuLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, StuLogsTable, StuLogsPrimaryKey...),
	)
}
func newClassStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClassInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ClassTable, ClassColumn),
	)
}
func newStudentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StudentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, StudentTable, StudentColumn),
	)
}
func newDormStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DormInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, DormTable, DormColumn),
	)
}
