// Code generated by ent, DO NOT EDIT.

package class

import (
	"eGZ-stu-log/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Class {
	return predicate.Class(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Class {
	return predicate.Class(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Class {
	return predicate.Class(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Class {
	return predicate.Class(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Class {
	return predicate.Class(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Class {
	return predicate.Class(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Class {
	return predicate.Class(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Class {
	return predicate.Class(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Class {
	return predicate.Class(sql.FieldLTE(FieldID, id))
}

// ClassName applies equality check predicate on the "className" field. It's identical to ClassNameEQ.
func ClassName(v string) predicate.Class {
	return predicate.Class(sql.FieldEQ(FieldClassName, v))
}

// ClassNameEQ applies the EQ predicate on the "className" field.
func ClassNameEQ(v string) predicate.Class {
	return predicate.Class(sql.FieldEQ(FieldClassName, v))
}

// ClassNameNEQ applies the NEQ predicate on the "className" field.
func ClassNameNEQ(v string) predicate.Class {
	return predicate.Class(sql.FieldNEQ(FieldClassName, v))
}

// ClassNameIn applies the In predicate on the "className" field.
func ClassNameIn(vs ...string) predicate.Class {
	return predicate.Class(sql.FieldIn(FieldClassName, vs...))
}

// ClassNameNotIn applies the NotIn predicate on the "className" field.
func ClassNameNotIn(vs ...string) predicate.Class {
	return predicate.Class(sql.FieldNotIn(FieldClassName, vs...))
}

// ClassNameGT applies the GT predicate on the "className" field.
func ClassNameGT(v string) predicate.Class {
	return predicate.Class(sql.FieldGT(FieldClassName, v))
}

// ClassNameGTE applies the GTE predicate on the "className" field.
func ClassNameGTE(v string) predicate.Class {
	return predicate.Class(sql.FieldGTE(FieldClassName, v))
}

// ClassNameLT applies the LT predicate on the "className" field.
func ClassNameLT(v string) predicate.Class {
	return predicate.Class(sql.FieldLT(FieldClassName, v))
}

// ClassNameLTE applies the LTE predicate on the "className" field.
func ClassNameLTE(v string) predicate.Class {
	return predicate.Class(sql.FieldLTE(FieldClassName, v))
}

// ClassNameContains applies the Contains predicate on the "className" field.
func ClassNameContains(v string) predicate.Class {
	return predicate.Class(sql.FieldContains(FieldClassName, v))
}

// ClassNameHasPrefix applies the HasPrefix predicate on the "className" field.
func ClassNameHasPrefix(v string) predicate.Class {
	return predicate.Class(sql.FieldHasPrefix(FieldClassName, v))
}

// ClassNameHasSuffix applies the HasSuffix predicate on the "className" field.
func ClassNameHasSuffix(v string) predicate.Class {
	return predicate.Class(sql.FieldHasSuffix(FieldClassName, v))
}

// ClassNameEqualFold applies the EqualFold predicate on the "className" field.
func ClassNameEqualFold(v string) predicate.Class {
	return predicate.Class(sql.FieldEqualFold(FieldClassName, v))
}

// ClassNameContainsFold applies the ContainsFold predicate on the "className" field.
func ClassNameContainsFold(v string) predicate.Class {
	return predicate.Class(sql.FieldContainsFold(FieldClassName, v))
}

// HasGrade applies the HasEdge predicate on the "grade" edge.
func HasGrade() predicate.Class {
	return predicate.Class(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GradeTable, GradeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGradeWith applies the HasEdge predicate on the "grade" edge with a given conditions (other predicates).
func HasGradeWith(preds ...predicate.Grade) predicate.Class {
	return predicate.Class(func(s *sql.Selector) {
		step := newGradeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStudent applies the HasEdge predicate on the "student" edge.
func HasStudent() predicate.Class {
	return predicate.Class(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, StudentTable, StudentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStudentWith applies the HasEdge predicate on the "student" edge with a given conditions (other predicates).
func HasStudentWith(preds ...predicate.Student) predicate.Class {
	return predicate.Class(func(s *sql.Selector) {
		step := newStudentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStuLogs applies the HasEdge predicate on the "stuLogs" edge.
func HasStuLogs() predicate.Class {
	return predicate.Class(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, StuLogsTable, StuLogsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStuLogsWith applies the HasEdge predicate on the "stuLogs" edge with a given conditions (other predicates).
func HasStuLogsWith(preds ...predicate.StuLog) predicate.Class {
	return predicate.Class(func(s *sql.Selector) {
		step := newStuLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Class) predicate.Class {
	return predicate.Class(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Class) predicate.Class {
	return predicate.Class(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Class) predicate.Class {
	return predicate.Class(sql.NotPredicates(p))
}
