// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eGZ-stu-log/internal/data/ent/class"
	"eGZ-stu-log/internal/data/ent/grade"
	"eGZ-stu-log/internal/data/ent/predicate"
	"eGZ-stu-log/internal/data/ent/student"
	"eGZ-stu-log/internal/data/ent/stulog"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClassUpdate is the builder for updating Class entities.
type ClassUpdate struct {
	config
	hooks    []Hook
	mutation *ClassMutation
}

// Where appends a list predicates to the ClassUpdate builder.
func (_u *ClassUpdate) Where(ps ...predicate.Class) *ClassUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClassName sets the "className" field.
func (_u *ClassUpdate) SetClassName(v string) *ClassUpdate {
	_u.mutation.SetClassName(v)
	return _u
}

// SetNillableClassName sets the "className" field if the given value is not nil.
func (_u *ClassUpdate) SetNillableClassName(v *string) *ClassUpdate {
	if v != nil {
		_u.SetClassName(*v)
	}
	return _u
}

// SetGradeID sets the "grade" edge to the Grade entity by ID.
func (_u *ClassUpdate) SetGradeID(id int64) *ClassUpdate {
	_u.mutation.SetGradeID(id)
	return _u
}

// SetGrade sets the "grade" edge to the Grade entity.
func (_u *ClassUpdate) SetGrade(v *Grade) *ClassUpdate {
	return _u.SetGradeID(v.ID)
}

// AddStudentIDs adds the "student" edge to the Student entity by IDs.
func (_u *ClassUpdate) AddStudentIDs(ids ...int64) *ClassUpdate {
	_u.mutation.AddStudentIDs(ids...)
	return _u
}

// AddStudent adds the "student" edges to the Student entity.
func (_u *ClassUpdate) AddStudent(v ...*Student) *ClassUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStudentIDs(ids...)
}

// AddStuLogIDs adds the "stuLogs" edge to the StuLog entity by IDs.
func (_u *ClassUpdate) AddStuLogIDs(ids ...int64) *ClassUpdate {
	_u.mutation.AddStuLogIDs(ids...)
	return _u
}

// AddStuLogs adds the "stuLogs" edges to the StuLog entity.
func (_u *ClassUpdate) AddStuLogs(v ...*StuLog) *ClassUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStuLogIDs(ids...)
}

// Mutation returns the ClassMutation object of the builder.
func (_u *ClassUpdate) Mutation() *ClassMutation {
	return _u.mutation
}

// ClearGrade clears the "grade" edge to the Grade entity.
func (_u *ClassUpdate) ClearGrade() *ClassUpdate {
	_u.mutation.ClearGrade()
	return _u
}

// ClearStudent clears all "student" edges to the Student entity.
func (_u *ClassUpdate) ClearStudent() *ClassUpdate {
	_u.mutation.ClearStudent()
	return _u
}

// RemoveStudentIDs removes the "student" edge to Student entities by IDs.
func (_u *ClassUpdate) RemoveStudentIDs(ids ...int64) *ClassUpdate {
	_u.mutation.RemoveStudentIDs(ids...)
	return _u
}

// RemoveStudent removes "student" edges to Student entities.
func (_u *ClassUpdate) RemoveStudent(v ...*Student) *ClassUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStudentIDs(ids...)
}

// ClearStuLogs clears all "stuLogs" edges to the StuLog entity.
func (_u *ClassUpdate) ClearStuLogs() *ClassUpdate {
	_u.mutation.ClearStuLogs()
	return _u
}

// RemoveStuLogIDs removes the "stuLogs" edge to StuLog entities by IDs.
func (_u *ClassUpdate) RemoveStuLogIDs(ids ...int64) *ClassUpdate {
	_u.mutation.RemoveStuLogIDs(ids...)
	return _u
}

// RemoveStuLogs removes "stuLogs" edges to StuLog entities.
func (_u *ClassUpdate) RemoveStuLogs(v ...*StuLog) *ClassUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStuLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClassUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClassUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClassUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClassUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClassUpdate) check() error {
	if _u.mutation.GradeCleared() && len(_u.mutation.GradeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Class.grade"`)
	}
	return nil
}

func (_u *ClassUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(class.Table, class.Columns, sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClassName(); ok {
		_spec.SetField(class.FieldClassName, field.TypeString, value)
	}
	if _u.mutation.GradeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.GradeTable,
			Columns: []string{class.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GradeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.GradeTable,
			Columns: []string{class.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStudentIDs(); len(nodes) > 0 && !_u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StuLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   class.StuLogsTable,
			Columns: class.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStuLogsIDs(); len(nodes) > 0 && !_u.mutation.StuLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   class.StuLogsTable,
			Columns: class.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StuLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   class.StuLogsTable,
			Columns: class.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClassUpdateOne is the builder for updating a single Class entity.
type ClassUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClassMutation
}

// SetClassName sets the "className" field.
func (_u *ClassUpdateOne) SetClassName(v string) *ClassUpdateOne {
	_u.mutation.SetClassName(v)
	return _u
}

// SetNillableClassName sets the "className" field if the given value is not nil.
func (_u *ClassUpdateOne) SetNillableClassName(v *string) *ClassUpdateOne {
	if v != nil {
		_u.SetClassName(*v)
	}
	return _u
}

// SetGradeID sets the "grade" edge to the Grade entity by ID.
func (_u *ClassUpdateOne) SetGradeID(id int64) *ClassUpdateOne {
	_u.mutation.SetGradeID(id)
	return _u
}

// SetGrade sets the "grade" edge to the Grade entity.
func (_u *ClassUpdateOne) SetGrade(v *Grade) *ClassUpdateOne {
	return _u.SetGradeID(v.ID)
}

// AddStudentIDs adds the "student" edge to the Student entity by IDs.
func (_u *ClassUpdateOne) AddStudentIDs(ids ...int64) *ClassUpdateOne {
	_u.mutation.AddStudentIDs(ids...)
	return _u
}

// AddStudent adds the "student" edges to the Student entity.
func (_u *ClassUpdateOne) AddStudent(v ...*Student) *ClassUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStudentIDs(ids...)
}

// AddStuLogIDs adds the "stuLogs" edge to the StuLog entity by IDs.
func (_u *ClassUpdateOne) AddStuLogIDs(ids ...int64) *ClassUpdateOne {
	_u.mutation.AddStuLogIDs(ids...)
	return _u
}

// AddStuLogs adds the "stuLogs" edges to the StuLog entity.
func (_u *ClassUpdateOne) AddStuLogs(v ...*StuLog) *ClassUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStuLogIDs(ids...)
}

// Mutation returns the ClassMutation object of the builder.
func (_u *ClassUpdateOne) Mutation() *ClassMutation {
	return _u.mutation
}

// ClearGrade clears the "grade" edge to the Grade entity.
func (_u *ClassUpdateOne) ClearGrade() *ClassUpdateOne {
	_u.mutation.ClearGrade()
	return _u
}

// ClearStudent clears all "student" edges to the Student entity.
func (_u *ClassUpdateOne) ClearStudent() *ClassUpdateOne {
	_u.mutation.ClearStudent()
	return _u
}

// RemoveStudentIDs removes the "student" edge to Student entities by IDs.
func (_u *ClassUpdateOne) RemoveStudentIDs(ids ...int64) *ClassUpdateOne {
	_u.mutation.RemoveStudentIDs(ids...)
	return _u
}

// RemoveStudent removes "student" edges to Student entities.
func (_u *ClassUpdateOne) RemoveStudent(v ...*Student) *ClassUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStudentIDs(ids...)
}

// ClearStuLogs clears all "stuLogs" edges to the StuLog entity.
func (_u *ClassUpdateOne) ClearStuLogs() *ClassUpdateOne {
	_u.mutation.ClearStuLogs()
	return _u
}

// RemoveStuLogIDs removes the "stuLogs" edge to StuLog entities by IDs.
func (_u *ClassUpdateOne) RemoveStuLogIDs(ids ...int64) *ClassUpdateOne {
	_u.mutation.RemoveStuLogIDs(ids...)
	return _u
}

// RemoveStuLogs removes "stuLogs" edges to StuLog entities.
func (_u *ClassUpdateOne) RemoveStuLogs(v ...*StuLog) *ClassUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStuLogIDs(ids...)
}

// Where appends a list predicates to the ClassUpdate builder.
func (_u *ClassUpdateOne) Where(ps ...predicate.Class) *ClassUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClassUpdateOne) Select(field string, fields ...string) *ClassUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Class entity.
func (_u *ClassUpdateOne) Save(ctx context.Context) (*Class, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClassUpdateOne) SaveX(ctx context.Context) *Class {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClassUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClassUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClassUpdateOne) check() error {
	if _u.mutation.GradeCleared() && len(_u.mutation.GradeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Class.grade"`)
	}
	return nil
}

func (_u *ClassUpdateOne) sqlSave(ctx context.Context) (_node *Class, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(class.Table, class.Columns, sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Class.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, class.FieldID)
		for _, f := range fields {
			if !class.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != class.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClassName(); ok {
		_spec.SetField(class.FieldClassName, field.TypeString, value)
	}
	if _u.mutation.GradeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.GradeTable,
			Columns: []string{class.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GradeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.GradeTable,
			Columns: []string{class.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStudentIDs(); len(nodes) > 0 && !_u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StuLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   class.StuLogsTable,
			Columns: class.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStuLogsIDs(); len(nodes) > 0 && !_u.mutation.StuLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   class.StuLogsTable,
			Columns: class.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StuLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   class.StuLogsTable,
			Columns: class.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Class{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
