// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eGZ-stu-log/internal/data/ent/class"
	"eGZ-stu-log/internal/data/ent/grade"
	"eGZ-stu-log/internal/data/ent/student"
	"eGZ-stu-log/internal/data/ent/stulog"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClassCreate is the builder for creating a Class entity.
type ClassCreate struct {
	config
	mutation *ClassMutation
	hooks    []Hook
}

// SetClassName sets the "className" field.
func (_c *ClassCreate) SetClassName(v string) *ClassCreate {
	_c.mutation.SetClassName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ClassCreate) SetID(v int64) *ClassCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGradeID sets the "grade" edge to the Grade entity by ID.
func (_c *ClassCreate) SetGradeID(id int64) *ClassCreate {
	_c.mutation.SetGradeID(id)
	return _c
}

// SetGrade sets the "grade" edge to the Grade entity.
func (_c *ClassCreate) SetGrade(v *Grade) *ClassCreate {
	return _c.SetGradeID(v.ID)
}

// AddStudentIDs adds the "student" edge to the Student entity by IDs.
func (_c *ClassCreate) AddStudentIDs(ids ...int64) *ClassCreate {
	_c.mutation.AddStudentIDs(ids...)
	return _c
}

// AddStudent adds the "student" edges to the Student entity.
func (_c *ClassCreate) AddStudent(v ...*Student) *ClassCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStudentIDs(ids...)
}

// AddStuLogIDs adds the "stuLogs" edge to the StuLog entity by IDs.
func (_c *ClassCreate) AddStuLogIDs(ids ...int64) *ClassCreate {
	_c.mutation.AddStuLogIDs(ids...)
	return _c
}

// AddStuLogs adds the "stuLogs" edges to the StuLog entity.
func (_c *ClassCreate) AddStuLogs(v ...*StuLog) *ClassCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStuLogIDs(ids...)
}

// Mutation returns the ClassMutation object of the builder.
func (_c *ClassCreate) Mutation() *ClassMutation {
	return _c.mutation
}

// Save creates the Class in the database.
func (_c *ClassCreate) Save(ctx context.Context) (*Class, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClassCreate) SaveX(ctx context.Context) *Class {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClassCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClassCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClassCreate) check() error {
	if _, ok := _c.mutation.ClassName(); !ok {
		return &ValidationError{Name: "className", err: errors.New(`ent: missing required field "Class.className"`)}
	}
	if len(_c.mutation.GradeIDs()) == 0 {
		return &ValidationError{Name: "grade", err: errors.New(`ent: missing required edge "Class.grade"`)}
	}
	return nil
}

func (_c *ClassCreate) sqlSave(ctx context.Context) (*Class, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClassCreate) createSpec() (*Class, *sqlgraph.CreateSpec) {
	var (
		_node = &Class{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(class.Table, sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ClassName(); ok {
		_spec.SetField(class.FieldClassName, field.TypeString, value)
		_node.ClassName = value
	}
	if nodes := _c.mutation.GradeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.GradeTable,
			Columns: []string{class.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.class_grade = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   class.StudentTable,
			Columns: []string{class.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StuLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   class.StuLogsTable,
			Columns: class.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClassCreateBulk is the builder for creating many Class entities in bulk.
type ClassCreateBulk struct {
	config
	err      error
	builders []*ClassCreate
}

// Save creates the Class entities in the database.
func (_c *ClassCreateBulk) Save(ctx context.Context) ([]*Class, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Class, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClassMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClassCreateBulk) SaveX(ctx context.Context) []*Class {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClassCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClassCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
