// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eGZ-stu-log/internal/data/ent/dorm"
	"eGZ-stu-log/internal/data/ent/grade"
	"eGZ-stu-log/internal/data/ent/predicate"
	"eGZ-stu-log/internal/data/ent/student"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DormUpdate is the builder for updating Dorm entities.
type DormUpdate struct {
	config
	hooks    []Hook
	mutation *DormMutation
}

// Where appends a list predicates to the DormUpdate builder.
func (_u *DormUpdate) Where(ps ...predicate.Dorm) *DormUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBuilding sets the "building" field.
func (_u *DormUpdate) SetBuilding(v string) *DormUpdate {
	_u.mutation.SetBuilding(v)
	return _u
}

// SetNillableBuilding sets the "building" field if the given value is not nil.
func (_u *DormUpdate) SetNillableBuilding(v *string) *DormUpdate {
	if v != nil {
		_u.SetBuilding(*v)
	}
	return _u
}

// SetDormNum sets the "dormNum" field.
func (_u *DormUpdate) SetDormNum(v string) *DormUpdate {
	_u.mutation.SetDormNum(v)
	return _u
}

// SetNillableDormNum sets the "dormNum" field if the given value is not nil.
func (_u *DormUpdate) SetNillableDormNum(v *string) *DormUpdate {
	if v != nil {
		_u.SetDormNum(*v)
	}
	return _u
}

// SetSex sets the "sex" field.
func (_u *DormUpdate) SetSex(v string) *DormUpdate {
	_u.mutation.SetSex(v)
	return _u
}

// SetNillableSex sets the "sex" field if the given value is not nil.
func (_u *DormUpdate) SetNillableSex(v *string) *DormUpdate {
	if v != nil {
		_u.SetSex(*v)
	}
	return _u
}

// AddStudentIDs adds the "student" edge to the Student entity by IDs.
func (_u *DormUpdate) AddStudentIDs(ids ...int64) *DormUpdate {
	_u.mutation.AddStudentIDs(ids...)
	return _u
}

// AddStudent adds the "student" edges to the Student entity.
func (_u *DormUpdate) AddStudent(v ...*Student) *DormUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStudentIDs(ids...)
}

// SetGradeID sets the "grade" edge to the Grade entity by ID.
func (_u *DormUpdate) SetGradeID(id int64) *DormUpdate {
	_u.mutation.SetGradeID(id)
	return _u
}

// SetGrade sets the "grade" edge to the Grade entity.
func (_u *DormUpdate) SetGrade(v *Grade) *DormUpdate {
	return _u.SetGradeID(v.ID)
}

// Mutation returns the DormMutation object of the builder.
func (_u *DormUpdate) Mutation() *DormMutation {
	return _u.mutation
}

// ClearStudent clears all "student" edges to the Student entity.
func (_u *DormUpdate) ClearStudent() *DormUpdate {
	_u.mutation.ClearStudent()
	return _u
}

// RemoveStudentIDs removes the "student" edge to Student entities by IDs.
func (_u *DormUpdate) RemoveStudentIDs(ids ...int64) *DormUpdate {
	_u.mutation.RemoveStudentIDs(ids...)
	return _u
}

// RemoveStudent removes "student" edges to Student entities.
func (_u *DormUpdate) RemoveStudent(v ...*Student) *DormUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStudentIDs(ids...)
}

// ClearGrade clears the "grade" edge to the Grade entity.
func (_u *DormUpdate) ClearGrade() *DormUpdate {
	_u.mutation.ClearGrade()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DormUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DormUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DormUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DormUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DormUpdate) check() error {
	if _u.mutation.GradeCleared() && len(_u.mutation.GradeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dorm.grade"`)
	}
	return nil
}

func (_u *DormUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dorm.Table, dorm.Columns, sqlgraph.NewFieldSpec(dorm.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Building(); ok {
		_spec.SetField(dorm.FieldBuilding, field.TypeString, value)
	}
	if value, ok := _u.mutation.DormNum(); ok {
		_spec.SetField(dorm.FieldDormNum, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sex(); ok {
		_spec.SetField(dorm.FieldSex, field.TypeString, value)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   dorm.StudentTable,
			Columns: []string{dorm.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStudentIDs(); len(nodes) > 0 && !_u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   dorm.StudentTable,
			Columns: []string{dorm.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   dorm.StudentTable,
			Columns: []string{dorm.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GradeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dorm.GradeTable,
			Columns: []string{dorm.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GradeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dorm.GradeTable,
			Columns: []string{dorm.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dorm.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DormUpdateOne is the builder for updating a single Dorm entity.
type DormUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DormMutation
}

// SetBuilding sets the "building" field.
func (_u *DormUpdateOne) SetBuilding(v string) *DormUpdateOne {
	_u.mutation.SetBuilding(v)
	return _u
}

// SetNillableBuilding sets the "building" field if the given value is not nil.
func (_u *DormUpdateOne) SetNillableBuilding(v *string) *DormUpdateOne {
	if v != nil {
		_u.SetBuilding(*v)
	}
	return _u
}

// SetDormNum sets the "dormNum" field.
func (_u *DormUpdateOne) SetDormNum(v string) *DormUpdateOne {
	_u.mutation.SetDormNum(v)
	return _u
}

// SetNillableDormNum sets the "dormNum" field if the given value is not nil.
func (_u *DormUpdateOne) SetNillableDormNum(v *string) *DormUpdateOne {
	if v != nil {
		_u.SetDormNum(*v)
	}
	return _u
}

// SetSex sets the "sex" field.
func (_u *DormUpdateOne) SetSex(v string) *DormUpdateOne {
	_u.mutation.SetSex(v)
	return _u
}

// SetNillableSex sets the "sex" field if the given value is not nil.
func (_u *DormUpdateOne) SetNillableSex(v *string) *DormUpdateOne {
	if v != nil {
		_u.SetSex(*v)
	}
	return _u
}

// AddStudentIDs adds the "student" edge to the Student entity by IDs.
func (_u *DormUpdateOne) AddStudentIDs(ids ...int64) *DormUpdateOne {
	_u.mutation.AddStudentIDs(ids...)
	return _u
}

// AddStudent adds the "student" edges to the Student entity.
func (_u *DormUpdateOne) AddStudent(v ...*Student) *DormUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStudentIDs(ids...)
}

// SetGradeID sets the "grade" edge to the Grade entity by ID.
func (_u *DormUpdateOne) SetGradeID(id int64) *DormUpdateOne {
	_u.mutation.SetGradeID(id)
	return _u
}

// SetGrade sets the "grade" edge to the Grade entity.
func (_u *DormUpdateOne) SetGrade(v *Grade) *DormUpdateOne {
	return _u.SetGradeID(v.ID)
}

// Mutation returns the DormMutation object of the builder.
func (_u *DormUpdateOne) Mutation() *DormMutation {
	return _u.mutation
}

// ClearStudent clears all "student" edges to the Student entity.
func (_u *DormUpdateOne) ClearStudent() *DormUpdateOne {
	_u.mutation.ClearStudent()
	return _u
}

// RemoveStudentIDs removes the "student" edge to Student entities by IDs.
func (_u *DormUpdateOne) RemoveStudentIDs(ids ...int64) *DormUpdateOne {
	_u.mutation.RemoveStudentIDs(ids...)
	return _u
}

// RemoveStudent removes "student" edges to Student entities.
func (_u *DormUpdateOne) RemoveStudent(v ...*Student) *DormUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStudentIDs(ids...)
}

// ClearGrade clears the "grade" edge to the Grade entity.
func (_u *DormUpdateOne) ClearGrade() *DormUpdateOne {
	_u.mutation.ClearGrade()
	return _u
}

// Where appends a list predicates to the DormUpdate builder.
func (_u *DormUpdateOne) Where(ps ...predicate.Dorm) *DormUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DormUpdateOne) Select(field string, fields ...string) *DormUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dorm entity.
func (_u *DormUpdateOne) Save(ctx context.Context) (*Dorm, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DormUpdateOne) SaveX(ctx context.Context) *Dorm {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DormUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DormUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DormUpdateOne) check() error {
	if _u.mutation.GradeCleared() && len(_u.mutation.GradeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dorm.grade"`)
	}
	return nil
}

func (_u *DormUpdateOne) sqlSave(ctx context.Context) (_node *Dorm, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dorm.Table, dorm.Columns, sqlgraph.NewFieldSpec(dorm.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dorm.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dorm.FieldID)
		for _, f := range fields {
			if !dorm.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dorm.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Building(); ok {
		_spec.SetField(dorm.FieldBuilding, field.TypeString, value)
	}
	if value, ok := _u.mutation.DormNum(); ok {
		_spec.SetField(dorm.FieldDormNum, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sex(); ok {
		_spec.SetField(dorm.FieldSex, field.TypeString, value)
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   dorm.StudentTable,
			Columns: []string{dorm.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStudentIDs(); len(nodes) > 0 && !_u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   dorm.StudentTable,
			Columns: []string{dorm.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   dorm.StudentTable,
			Columns: []string{dorm.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GradeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dorm.GradeTable,
			Columns: []string{dorm.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GradeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dorm.GradeTable,
			Columns: []string{dorm.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Dorm{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dorm.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
