// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eGZ-stu-log/internal/data/ent/image"
	"eGZ-stu-log/internal/data/ent/predicate"
	"eGZ-stu-log/internal/data/ent/stulog"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ImageUpdate is the builder for updating Image entities.
type ImageUpdate struct {
	config
	hooks    []Hook
	mutation *ImageMutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (_u *ImageUpdate) Where(ps ...predicate.Image) *ImageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetImageUrl sets the "imageUrl" field.
func (_u *ImageUpdate) SetImageUrl(v string) *ImageUpdate {
	_u.mutation.SetImageUrl(v)
	return _u
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableImageUrl(v *string) *ImageUpdate {
	if v != nil {
		_u.SetImageUrl(*v)
	}
	return _u
}

// AddStuLogIDs adds the "stuLogs" edge to the StuLog entity by IDs.
func (_u *ImageUpdate) AddStuLogIDs(ids ...int64) *ImageUpdate {
	_u.mutation.AddStuLogIDs(ids...)
	return _u
}

// AddStuLogs adds the "stuLogs" edges to the StuLog entity.
func (_u *ImageUpdate) AddStuLogs(v ...*StuLog) *ImageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStuLogIDs(ids...)
}

// Mutation returns the ImageMutation object of the builder.
func (_u *ImageUpdate) Mutation() *ImageMutation {
	return _u.mutation
}

// ClearStuLogs clears all "stuLogs" edges to the StuLog entity.
func (_u *ImageUpdate) ClearStuLogs() *ImageUpdate {
	_u.mutation.ClearStuLogs()
	return _u
}

// RemoveStuLogIDs removes the "stuLogs" edge to StuLog entities by IDs.
func (_u *ImageUpdate) RemoveStuLogIDs(ids ...int64) *ImageUpdate {
	_u.mutation.RemoveStuLogIDs(ids...)
	return _u
}

// RemoveStuLogs removes "stuLogs" edges to StuLog entities.
func (_u *ImageUpdate) RemoveStuLogs(v ...*StuLog) *ImageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStuLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ImageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ImageUrl(); ok {
		_spec.SetField(image.FieldImageUrl, field.TypeString, value)
	}
	if _u.mutation.StuLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   image.StuLogsTable,
			Columns: image.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStuLogsIDs(); len(nodes) > 0 && !_u.mutation.StuLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   image.StuLogsTable,
			Columns: image.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StuLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   image.StuLogsTable,
			Columns: image.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageUpdateOne is the builder for updating a single Image entity.
type ImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageMutation
}

// SetImageUrl sets the "imageUrl" field.
func (_u *ImageUpdateOne) SetImageUrl(v string) *ImageUpdateOne {
	_u.mutation.SetImageUrl(v)
	return _u
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableImageUrl(v *string) *ImageUpdateOne {
	if v != nil {
		_u.SetImageUrl(*v)
	}
	return _u
}

// AddStuLogIDs adds the "stuLogs" edge to the StuLog entity by IDs.
func (_u *ImageUpdateOne) AddStuLogIDs(ids ...int64) *ImageUpdateOne {
	_u.mutation.AddStuLogIDs(ids...)
	return _u
}

// AddStuLogs adds the "stuLogs" edges to the StuLog entity.
func (_u *ImageUpdateOne) AddStuLogs(v ...*StuLog) *ImageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStuLogIDs(ids...)
}

// Mutation returns the ImageMutation object of the builder.
func (_u *ImageUpdateOne) Mutation() *ImageMutation {
	return _u.mutation
}

// ClearStuLogs clears all "stuLogs" edges to the StuLog entity.
func (_u *ImageUpdateOne) ClearStuLogs() *ImageUpdateOne {
	_u.mutation.ClearStuLogs()
	return _u
}

// RemoveStuLogIDs removes the "stuLogs" edge to StuLog entities by IDs.
func (_u *ImageUpdateOne) RemoveStuLogIDs(ids ...int64) *ImageUpdateOne {
	_u.mutation.RemoveStuLogIDs(ids...)
	return _u
}

// RemoveStuLogs removes "stuLogs" edges to StuLog entities.
func (_u *ImageUpdateOne) RemoveStuLogs(v ...*StuLog) *ImageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStuLogIDs(ids...)
}

// Where appends a list predicates to the ImageUpdate builder.
func (_u *ImageUpdateOne) Where(ps ...predicate.Image) *ImageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageUpdateOne) Select(field string, fields ...string) *ImageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Image entity.
func (_u *ImageUpdateOne) Save(ctx context.Context) (*Image, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageUpdateOne) SaveX(ctx context.Context) *Image {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ImageUpdateOne) sqlSave(ctx context.Context) (_node *Image, err error) {
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Image.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, image.FieldID)
		for _, f := range fields {
			if !image.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != image.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ImageUrl(); ok {
		_spec.SetField(image.FieldImageUrl, field.TypeString, value)
	}
	if _u.mutation.StuLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   image.StuLogsTable,
			Columns: image.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStuLogsIDs(); len(nodes) > 0 && !_u.mutation.StuLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   image.StuLogsTable,
			Columns: image.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StuLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   image.StuLogsTable,
			Columns: image.StuLogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Image{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
