// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eGZ-stu-log/internal/data/ent/class"
	"eGZ-stu-log/internal/data/ent/dorm"
	"eGZ-stu-log/internal/data/ent/grade"
	"eGZ-stu-log/internal/data/ent/student"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudentCreate is the builder for creating a Student entity.
type StudentCreate struct {
	config
	mutation *StudentMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *StudentCreate) SetName(v string) *StudentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSex sets the "sex" field.
func (_c *StudentCreate) SetSex(v string) *StudentCreate {
	_c.mutation.SetSex(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *StudentCreate) SetScore(v int) *StudentCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *StudentCreate) SetNillableScore(v *int) *StudentCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetGradeID sets the "grade" edge to the Grade entity by ID.
func (_c *StudentCreate) SetGradeID(id int) *StudentCreate {
	_c.mutation.SetGradeID(id)
	return _c
}

// SetGrade sets the "grade" edge to the Grade entity.
func (_c *StudentCreate) SetGrade(v *Grade) *StudentCreate {
	return _c.SetGradeID(v.ID)
}

// SetClassID sets the "class" edge to the Class entity by ID.
func (_c *StudentCreate) SetClassID(id int) *StudentCreate {
	_c.mutation.SetClassID(id)
	return _c
}

// SetClass sets the "class" edge to the Class entity.
func (_c *StudentCreate) SetClass(v *Class) *StudentCreate {
	return _c.SetClassID(v.ID)
}

// SetDormID sets the "dorm" edge to the Dorm entity by ID.
func (_c *StudentCreate) SetDormID(id int) *StudentCreate {
	_c.mutation.SetDormID(id)
	return _c
}

// SetNillableDormID sets the "dorm" edge to the Dorm entity by ID if the given value is not nil.
func (_c *StudentCreate) SetNillableDormID(id *int) *StudentCreate {
	if id != nil {
		_c = _c.SetDormID(*id)
	}
	return _c
}

// SetDorm sets the "dorm" edge to the Dorm entity.
func (_c *StudentCreate) SetDorm(v *Dorm) *StudentCreate {
	return _c.SetDormID(v.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (_c *StudentCreate) Mutation() *StudentMutation {
	return _c.mutation
}

// Save creates the Student in the database.
func (_c *StudentCreate) Save(ctx context.Context) (*Student, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StudentCreate) SaveX(ctx context.Context) *Student {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StudentCreate) defaults() {
	if _, ok := _c.mutation.Score(); !ok {
		v := student.DefaultScore
		_c.mutation.SetScore(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StudentCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Student.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := student.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Student.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sex(); !ok {
		return &ValidationError{Name: "sex", err: errors.New(`ent: missing required field "Student.sex"`)}
	}
	if v, ok := _c.mutation.Sex(); ok {
		if err := student.SexValidator(v); err != nil {
			return &ValidationError{Name: "sex", err: fmt.Errorf(`ent: validator failed for field "Student.sex": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "Student.score"`)}
	}
	if len(_c.mutation.GradeIDs()) == 0 {
		return &ValidationError{Name: "grade", err: errors.New(`ent: missing required edge "Student.grade"`)}
	}
	if len(_c.mutation.ClassIDs()) == 0 {
		return &ValidationError{Name: "class", err: errors.New(`ent: missing required edge "Student.class"`)}
	}
	return nil
}

func (_c *StudentCreate) sqlSave(ctx context.Context) (*Student, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StudentCreate) createSpec() (*Student, *sqlgraph.CreateSpec) {
	var (
		_node = &Student{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(student.Table, sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(student.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Sex(); ok {
		_spec.SetField(student.FieldSex, field.TypeString, value)
		_node.Sex = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(student.FieldScore, field.TypeInt, value)
		_node.Score = value
	}
	if nodes := _c.mutation.GradeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.GradeTable,
			Columns: []string{student.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.student_grade = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.student_class = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DormIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.DormTable,
			Columns: []string{student.DormColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dorm.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.student_dorm = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StudentCreateBulk is the builder for creating many Student entities in bulk.
type StudentCreateBulk struct {
	config
	err      error
	builders []*StudentCreate
}

// Save creates the Student entities in the database.
func (_c *StudentCreateBulk) Save(ctx context.Context) ([]*Student, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Student, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StudentCreateBulk) SaveX(ctx context.Context) []*Student {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
