// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eGZ-stu-log/internal/data/ent/class"
	"eGZ-stu-log/internal/data/ent/dorm"
	"eGZ-stu-log/internal/data/ent/grade"
	"eGZ-stu-log/internal/data/ent/predicate"
	"eGZ-stu-log/internal/data/ent/student"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudentUpdate is the builder for updating Student entities.
type StudentUpdate struct {
	config
	hooks    []Hook
	mutation *StudentMutation
}

// Where appends a list predicates to the StudentUpdate builder.
func (_u *StudentUpdate) Where(ps ...predicate.Student) *StudentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StudentUpdate) SetName(v string) *StudentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableName(v *string) *StudentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSex sets the "sex" field.
func (_u *StudentUpdate) SetSex(v string) *StudentUpdate {
	_u.mutation.SetSex(v)
	return _u
}

// SetNillableSex sets the "sex" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableSex(v *string) *StudentUpdate {
	if v != nil {
		_u.SetSex(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *StudentUpdate) SetScore(v int) *StudentUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableScore(v *int) *StudentUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *StudentUpdate) AddScore(v int) *StudentUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetGradeID sets the "grade" edge to the Grade entity by ID.
func (_u *StudentUpdate) SetGradeID(id int) *StudentUpdate {
	_u.mutation.SetGradeID(id)
	return _u
}

// SetGrade sets the "grade" edge to the Grade entity.
func (_u *StudentUpdate) SetGrade(v *Grade) *StudentUpdate {
	return _u.SetGradeID(v.ID)
}

// SetClassID sets the "class" edge to the Class entity by ID.
func (_u *StudentUpdate) SetClassID(id int) *StudentUpdate {
	_u.mutation.SetClassID(id)
	return _u
}

// SetClass sets the "class" edge to the Class entity.
func (_u *StudentUpdate) SetClass(v *Class) *StudentUpdate {
	return _u.SetClassID(v.ID)
}

// SetDormID sets the "dorm" edge to the Dorm entity by ID.
func (_u *StudentUpdate) SetDormID(id int) *StudentUpdate {
	_u.mutation.SetDormID(id)
	return _u
}

// SetNillableDormID sets the "dorm" edge to the Dorm entity by ID if the given value is not nil.
func (_u *StudentUpdate) SetNillableDormID(id *int) *StudentUpdate {
	if id != nil {
		_u = _u.SetDormID(*id)
	}
	return _u
}

// SetDorm sets the "dorm" edge to the Dorm entity.
func (_u *StudentUpdate) SetDorm(v *Dorm) *StudentUpdate {
	return _u.SetDormID(v.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (_u *StudentUpdate) Mutation() *StudentMutation {
	return _u.mutation
}

// ClearGrade clears the "grade" edge to the Grade entity.
func (_u *StudentUpdate) ClearGrade() *StudentUpdate {
	_u.mutation.ClearGrade()
	return _u
}

// ClearClass clears the "class" edge to the Class entity.
func (_u *StudentUpdate) ClearClass() *StudentUpdate {
	_u.mutation.ClearClass()
	return _u
}

// ClearDorm clears the "dorm" edge to the Dorm entity.
func (_u *StudentUpdate) ClearDorm() *StudentUpdate {
	_u.mutation.ClearDorm()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StudentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StudentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StudentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StudentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StudentUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := student.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Student.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sex(); ok {
		if err := student.SexValidator(v); err != nil {
			return &ValidationError{Name: "sex", err: fmt.Errorf(`ent: validator failed for field "Student.sex": %w`, err)}
		}
	}
	if _u.mutation.GradeCleared() && len(_u.mutation.GradeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Student.grade"`)
	}
	if _u.mutation.ClassCleared() && len(_u.mutation.ClassIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Student.class"`)
	}
	return nil
}

func (_u *StudentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(student.Table, student.Columns, sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(student.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sex(); ok {
		_spec.SetField(student.FieldSex, field.TypeString, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(student.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(student.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.GradeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.GradeTable,
			Columns: []string{student.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GradeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.GradeTable,
			Columns: []string{student.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DormCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.DormTable,
			Columns: []string{student.DormColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dorm.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DormIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.DormTable,
			Columns: []string{student.DormColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dorm.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{student.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StudentUpdateOne is the builder for updating a single Student entity.
type StudentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StudentMutation
}

// SetName sets the "name" field.
func (_u *StudentUpdateOne) SetName(v string) *StudentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableName(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSex sets the "sex" field.
func (_u *StudentUpdateOne) SetSex(v string) *StudentUpdateOne {
	_u.mutation.SetSex(v)
	return _u
}

// SetNillableSex sets the "sex" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableSex(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetSex(*v)
	}
	return _u
}

// SetScore sets the "score" field.
func (_u *StudentUpdateOne) SetScore(v int) *StudentUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableScore(v *int) *StudentUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *StudentUpdateOne) AddScore(v int) *StudentUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetGradeID sets the "grade" edge to the Grade entity by ID.
func (_u *StudentUpdateOne) SetGradeID(id int) *StudentUpdateOne {
	_u.mutation.SetGradeID(id)
	return _u
}

// SetGrade sets the "grade" edge to the Grade entity.
func (_u *StudentUpdateOne) SetGrade(v *Grade) *StudentUpdateOne {
	return _u.SetGradeID(v.ID)
}

// SetClassID sets the "class" edge to the Class entity by ID.
func (_u *StudentUpdateOne) SetClassID(id int) *StudentUpdateOne {
	_u.mutation.SetClassID(id)
	return _u
}

// SetClass sets the "class" edge to the Class entity.
func (_u *StudentUpdateOne) SetClass(v *Class) *StudentUpdateOne {
	return _u.SetClassID(v.ID)
}

// SetDormID sets the "dorm" edge to the Dorm entity by ID.
func (_u *StudentUpdateOne) SetDormID(id int) *StudentUpdateOne {
	_u.mutation.SetDormID(id)
	return _u
}

// SetNillableDormID sets the "dorm" edge to the Dorm entity by ID if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableDormID(id *int) *StudentUpdateOne {
	if id != nil {
		_u = _u.SetDormID(*id)
	}
	return _u
}

// SetDorm sets the "dorm" edge to the Dorm entity.
func (_u *StudentUpdateOne) SetDorm(v *Dorm) *StudentUpdateOne {
	return _u.SetDormID(v.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (_u *StudentUpdateOne) Mutation() *StudentMutation {
	return _u.mutation
}

// ClearGrade clears the "grade" edge to the Grade entity.
func (_u *StudentUpdateOne) ClearGrade() *StudentUpdateOne {
	_u.mutation.ClearGrade()
	return _u
}

// ClearClass clears the "class" edge to the Class entity.
func (_u *StudentUpdateOne) ClearClass() *StudentUpdateOne {
	_u.mutation.ClearClass()
	return _u
}

// ClearDorm clears the "dorm" edge to the Dorm entity.
func (_u *StudentUpdateOne) ClearDorm() *StudentUpdateOne {
	_u.mutation.ClearDorm()
	return _u
}

// Where appends a list predicates to the StudentUpdate builder.
func (_u *StudentUpdateOne) Where(ps ...predicate.Student) *StudentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StudentUpdateOne) Select(field string, fields ...string) *StudentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Student entity.
func (_u *StudentUpdateOne) Save(ctx context.Context) (*Student, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StudentUpdateOne) SaveX(ctx context.Context) *Student {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StudentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StudentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StudentUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := student.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Student.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sex(); ok {
		if err := student.SexValidator(v); err != nil {
			return &ValidationError{Name: "sex", err: fmt.Errorf(`ent: validator failed for field "Student.sex": %w`, err)}
		}
	}
	if _u.mutation.GradeCleared() && len(_u.mutation.GradeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Student.grade"`)
	}
	if _u.mutation.ClassCleared() && len(_u.mutation.ClassIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Student.class"`)
	}
	return nil
}

func (_u *StudentUpdateOne) sqlSave(ctx context.Context) (_node *Student, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(student.Table, student.Columns, sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Student.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, student.FieldID)
		for _, f := range fields {
			if !student.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != student.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(student.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sex(); ok {
		_spec.SetField(student.FieldSex, field.TypeString, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(student.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(student.FieldScore, field.TypeInt, value)
	}
	if _u.mutation.GradeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.GradeTable,
			Columns: []string{student.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GradeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.GradeTable,
			Columns: []string{student.GradeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grade.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DormCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.DormTable,
			Columns: []string{student.DormColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dorm.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DormIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.DormTable,
			Columns: []string{student.DormColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dorm.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Student{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{student.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
