// Code generated by ent, DO NOT EDIT.

package ent

import (
	"eGZ-stu-log/internal/data/ent/dorm"
	"eGZ-stu-log/internal/data/ent/grade"
	"eGZ-stu-log/internal/data/ent/rule"
	"eGZ-stu-log/internal/data/ent/stulog"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// StuLog is the model entity for the StuLog schema.
type StuLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 违纪备注
	Content string `json:"content,omitempty"`
	// 是否被撤销
	Revoked bool `json:"revoked,omitempty"`
	// 加减分情况
	Score int32 `json:"score,omitempty"`
	// 违纪时间
	Time time.Time `json:"time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StuLogQuery when eager-loading is set.
	Edges         StuLogEdges `json:"edges"`
	stu_log_grade *int64
	stu_log_rule  *int64
	stu_log_dorm  *int64
	selectValues  sql.SelectValues
}

// StuLogEdges holds the relations/edges for other nodes in the graph.
type StuLogEdges struct {
	// Class holds the value of the class edge.
	Class []*Class `json:"class,omitempty"`
	// Grade holds the value of the grade edge.
	Grade *Grade `json:"grade,omitempty"`
	// Rule holds the value of the rule edge.
	Rule *Rule `json:"rule,omitempty"`
	// Students holds the value of the students edge.
	Students []*Student `json:"students,omitempty"`
	// Images holds the value of the images edge.
	Images []*Image `json:"images,omitempty"`
	// Dorm holds the value of the dorm edge.
	Dorm *Dorm `json:"dorm,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// ClassOrErr returns the Class value or an error if the edge
// was not loaded in eager-loading.
func (e StuLogEdges) ClassOrErr() ([]*Class, error) {
	if e.loadedTypes[0] {
		return e.Class, nil
	}
	return nil, &NotLoadedError{edge: "class"}
}

// GradeOrErr returns the Grade value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StuLogEdges) GradeOrErr() (*Grade, error) {
	if e.Grade != nil {
		return e.Grade, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: grade.Label}
	}
	return nil, &NotLoadedError{edge: "grade"}
}

// RuleOrErr returns the Rule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StuLogEdges) RuleOrErr() (*Rule, error) {
	if e.Rule != nil {
		return e.Rule, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: rule.Label}
	}
	return nil, &NotLoadedError{edge: "rule"}
}

// StudentsOrErr returns the Students value or an error if the edge
// was not loaded in eager-loading.
func (e StuLogEdges) StudentsOrErr() ([]*Student, error) {
	if e.loadedTypes[3] {
		return e.Students, nil
	}
	return nil, &NotLoadedError{edge: "students"}
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e StuLogEdges) ImagesOrErr() ([]*Image, error) {
	if e.loadedTypes[4] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// DormOrErr returns the Dorm value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StuLogEdges) DormOrErr() (*Dorm, error) {
	if e.Dorm != nil {
		return e.Dorm, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: dorm.Label}
	}
	return nil, &NotLoadedError{edge: "dorm"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StuLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stulog.FieldRevoked:
			values[i] = new(sql.NullBool)
		case stulog.FieldID, stulog.FieldScore:
			values[i] = new(sql.NullInt64)
		case stulog.FieldContent:
			values[i] = new(sql.NullString)
		case stulog.FieldTime:
			values[i] = new(sql.NullTime)
		case stulog.ForeignKeys[0]: // stu_log_grade
			values[i] = new(sql.NullInt64)
		case stulog.ForeignKeys[1]: // stu_log_rule
			values[i] = new(sql.NullInt64)
		case stulog.ForeignKeys[2]: // stu_log_dorm
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StuLog fields.
func (_m *StuLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stulog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case stulog.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case stulog.FieldRevoked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field revoked", values[i])
			} else if value.Valid {
				_m.Revoked = value.Bool
			}
		case stulog.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = int32(value.Int64)
			}
		case stulog.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				_m.Time = value.Time
			}
		case stulog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field stu_log_grade", value)
			} else if value.Valid {
				_m.stu_log_grade = new(int64)
				*_m.stu_log_grade = int64(value.Int64)
			}
		case stulog.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field stu_log_rule", value)
			} else if value.Valid {
				_m.stu_log_rule = new(int64)
				*_m.stu_log_rule = int64(value.Int64)
			}
		case stulog.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field stu_log_dorm", value)
			} else if value.Valid {
				_m.stu_log_dorm = new(int64)
				*_m.stu_log_dorm = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StuLog.
// This includes values selected through modifiers, order, etc.
func (_m *StuLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClass queries the "class" edge of the StuLog entity.
func (_m *StuLog) QueryClass() *ClassQuery {
	return NewStuLogClient(_m.config).QueryClass(_m)
}

// QueryGrade queries the "grade" edge of the StuLog entity.
func (_m *StuLog) QueryGrade() *GradeQuery {
	return NewStuLogClient(_m.config).QueryGrade(_m)
}

// QueryRule queries the "rule" edge of the StuLog entity.
func (_m *StuLog) QueryRule() *RuleQuery {
	return NewStuLogClient(_m.config).QueryRule(_m)
}

// QueryStudents queries the "students" edge of the StuLog entity.
func (_m *StuLog) QueryStudents() *StudentQuery {
	return NewStuLogClient(_m.config).QueryStudents(_m)
}

// QueryImages queries the "images" edge of the StuLog entity.
func (_m *StuLog) QueryImages() *ImageQuery {
	return NewStuLogClient(_m.config).QueryImages(_m)
}

// QueryDorm queries the "dorm" edge of the StuLog entity.
func (_m *StuLog) QueryDorm() *DormQuery {
	return NewStuLogClient(_m.config).QueryDorm(_m)
}

// Update returns a builder for updating this StuLog.
// Note that you need to call StuLog.Unwrap() before calling this method if this StuLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StuLog) Update() *StuLogUpdateOne {
	return NewStuLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StuLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StuLog) Unwrap() *StuLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StuLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StuLog) String() string {
	var builder strings.Builder
	builder.WriteString("StuLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("revoked=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revoked))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("time=")
	builder.WriteString(_m.Time.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StuLogs is a parsable slice of StuLog.
type StuLogs []*StuLog
