// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eGZ-stu-log/internal/data/ent/predicate"
	"eGZ-stu-log/internal/data/ent/stulog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StuLogDelete is the builder for deleting a StuLog entity.
type StuLogDelete struct {
	config
	hooks    []Hook
	mutation *StuLogMutation
}

// Where appends a list predicates to the StuLogDelete builder.
func (_d *StuLogDelete) Where(ps ...predicate.StuLog) *StuLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StuLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StuLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StuLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(stulog.Table, sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StuLogDeleteOne is the builder for deleting a single StuLog entity.
type StuLogDeleteOne struct {
	_d *StuLogDelete
}

// Where appends a list predicates to the StuLogDelete builder.
func (_d *StuLogDeleteOne) Where(ps ...predicate.StuLog) *StuLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StuLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{stulog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StuLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
