// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"eGZ-stu-log/internal/data/ent/class"
	"eGZ-stu-log/internal/data/ent/grade"
	"eGZ-stu-log/internal/data/ent/image"
	"eGZ-stu-log/internal/data/ent/predicate"
	"eGZ-stu-log/internal/data/ent/rule"
	"eGZ-stu-log/internal/data/ent/student"
	"eGZ-stu-log/internal/data/ent/stulog"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StuLogQuery is the builder for querying StuLog entities.
type StuLogQuery struct {
	config
	ctx          *QueryContext
	order        []stulog.OrderOption
	inters       []Interceptor
	predicates   []predicate.StuLog
	withClass    *ClassQuery
	withGrade    *GradeQuery
	withRule     *RuleQuery
	withStudents *StudentQuery
	withImages   *ImageQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StuLogQuery builder.
func (_q *StuLogQuery) Where(ps ...predicate.StuLog) *StuLogQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *StuLogQuery) Limit(limit int) *StuLogQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *StuLogQuery) Offset(offset int) *StuLogQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *StuLogQuery) Unique(unique bool) *StuLogQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *StuLogQuery) Order(o ...stulog.OrderOption) *StuLogQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryClass chains the current query on the "class" edge.
func (_q *StuLogQuery) QueryClass() *ClassQuery {
	query := (&ClassClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stulog.Table, stulog.FieldID, selector),
			sqlgraph.To(class.Table, class.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, stulog.ClassTable, stulog.ClassPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGrade chains the current query on the "grade" edge.
func (_q *StuLogQuery) QueryGrade() *GradeQuery {
	query := (&GradeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stulog.Table, stulog.FieldID, selector),
			sqlgraph.To(grade.Table, grade.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, stulog.GradeTable, stulog.GradeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRule chains the current query on the "rule" edge.
func (_q *StuLogQuery) QueryRule() *RuleQuery {
	query := (&RuleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stulog.Table, stulog.FieldID, selector),
			sqlgraph.To(rule.Table, rule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, stulog.RuleTable, stulog.RuleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStudents chains the current query on the "students" edge.
func (_q *StuLogQuery) QueryStudents() *StudentQuery {
	query := (&StudentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stulog.Table, stulog.FieldID, selector),
			sqlgraph.To(student.Table, student.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, stulog.StudentsTable, stulog.StudentsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryImages chains the current query on the "images" edge.
func (_q *StuLogQuery) QueryImages() *ImageQuery {
	query := (&ImageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stulog.Table, stulog.FieldID, selector),
			sqlgraph.To(image.Table, image.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, stulog.ImagesTable, stulog.ImagesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StuLog entity from the query.
// Returns a *NotFoundError when no StuLog was found.
func (_q *StuLogQuery) First(ctx context.Context) (*StuLog, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stulog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *StuLogQuery) FirstX(ctx context.Context) *StuLog {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StuLog ID from the query.
// Returns a *NotFoundError when no StuLog ID was found.
func (_q *StuLogQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stulog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *StuLogQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StuLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StuLog entity is found.
// Returns a *NotFoundError when no StuLog entities are found.
func (_q *StuLogQuery) Only(ctx context.Context) (*StuLog, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stulog.Label}
	default:
		return nil, &NotSingularError{stulog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *StuLogQuery) OnlyX(ctx context.Context) *StuLog {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StuLog ID in the query.
// Returns a *NotSingularError when more than one StuLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *StuLogQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stulog.Label}
	default:
		err = &NotSingularError{stulog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *StuLogQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StuLogs.
func (_q *StuLogQuery) All(ctx context.Context) ([]*StuLog, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StuLog, *StuLogQuery]()
	return withInterceptors[[]*StuLog](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *StuLogQuery) AllX(ctx context.Context) []*StuLog {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StuLog IDs.
func (_q *StuLogQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(stulog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *StuLogQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *StuLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*StuLogQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *StuLogQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *StuLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *StuLogQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StuLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *StuLogQuery) Clone() *StuLogQuery {
	if _q == nil {
		return nil
	}
	return &StuLogQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]stulog.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.StuLog{}, _q.predicates...),
		withClass:    _q.withClass.Clone(),
		withGrade:    _q.withGrade.Clone(),
		withRule:     _q.withRule.Clone(),
		withStudents: _q.withStudents.Clone(),
		withImages:   _q.withImages.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithClass tells the query-builder to eager-load the nodes that are connected to
// the "class" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StuLogQuery) WithClass(opts ...func(*ClassQuery)) *StuLogQuery {
	query := (&ClassClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClass = query
	return _q
}

// WithGrade tells the query-builder to eager-load the nodes that are connected to
// the "grade" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StuLogQuery) WithGrade(opts ...func(*GradeQuery)) *StuLogQuery {
	query := (&GradeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGrade = query
	return _q
}

// WithRule tells the query-builder to eager-load the nodes that are connected to
// the "rule" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StuLogQuery) WithRule(opts ...func(*RuleQuery)) *StuLogQuery {
	query := (&RuleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRule = query
	return _q
}

// WithStudents tells the query-builder to eager-load the nodes that are connected to
// the "students" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StuLogQuery) WithStudents(opts ...func(*StudentQuery)) *StuLogQuery {
	query := (&StudentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStudents = query
	return _q
}

// WithImages tells the query-builder to eager-load the nodes that are connected to
// the "images" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StuLogQuery) WithImages(opts ...func(*ImageQuery)) *StuLogQuery {
	query := (&ImageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withImages = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StuLog.Query().
//		GroupBy(stulog.FieldContent).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *StuLogQuery) GroupBy(field string, fields ...string) *StuLogGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StuLogGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = stulog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//	}
//
//	client.StuLog.Query().
//		Select(stulog.FieldContent).
//		Scan(ctx, &v)
func (_q *StuLogQuery) Select(fields ...string) *StuLogSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &StuLogSelect{StuLogQuery: _q}
	sbuild.label = stulog.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StuLogSelect configured with the given aggregations.
func (_q *StuLogQuery) Aggregate(fns ...AggregateFunc) *StuLogSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *StuLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !stulog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *StuLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StuLog, error) {
	var (
		nodes       = []*StuLog{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withClass != nil,
			_q.withGrade != nil,
			_q.withRule != nil,
			_q.withStudents != nil,
			_q.withImages != nil,
		}
	)
	if _q.withGrade != nil || _q.withRule != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, stulog.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StuLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StuLog{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withClass; query != nil {
		if err := _q.loadClass(ctx, query, nodes,
			func(n *StuLog) { n.Edges.Class = []*Class{} },
			func(n *StuLog, e *Class) { n.Edges.Class = append(n.Edges.Class, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGrade; query != nil {
		if err := _q.loadGrade(ctx, query, nodes, nil,
			func(n *StuLog, e *Grade) { n.Edges.Grade = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRule; query != nil {
		if err := _q.loadRule(ctx, query, nodes, nil,
			func(n *StuLog, e *Rule) { n.Edges.Rule = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStudents; query != nil {
		if err := _q.loadStudents(ctx, query, nodes,
			func(n *StuLog) { n.Edges.Students = []*Student{} },
			func(n *StuLog, e *Student) { n.Edges.Students = append(n.Edges.Students, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withImages; query != nil {
		if err := _q.loadImages(ctx, query, nodes,
			func(n *StuLog) { n.Edges.Images = []*Image{} },
			func(n *StuLog, e *Image) { n.Edges.Images = append(n.Edges.Images, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *StuLogQuery) loadClass(ctx context.Context, query *ClassQuery, nodes []*StuLog, init func(*StuLog), assign func(*StuLog, *Class)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int64]*StuLog)
	nids := make(map[int64]map[*StuLog]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(stulog.ClassTable)
		s.Join(joinT).On(s.C(class.FieldID), joinT.C(stulog.ClassPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(stulog.ClassPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(stulog.ClassPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullInt64).Int64
				inValue := values[1].(*sql.NullInt64).Int64
				if nids[inValue] == nil {
					nids[inValue] = map[*StuLog]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Class](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "class" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *StuLogQuery) loadGrade(ctx context.Context, query *GradeQuery, nodes []*StuLog, init func(*StuLog), assign func(*StuLog, *Grade)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*StuLog)
	for i := range nodes {
		if nodes[i].stu_log_grade == nil {
			continue
		}
		fk := *nodes[i].stu_log_grade
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(grade.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "stu_log_grade" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *StuLogQuery) loadRule(ctx context.Context, query *RuleQuery, nodes []*StuLog, init func(*StuLog), assign func(*StuLog, *Rule)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*StuLog)
	for i := range nodes {
		if nodes[i].stu_log_rule == nil {
			continue
		}
		fk := *nodes[i].stu_log_rule
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rule.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "stu_log_rule" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *StuLogQuery) loadStudents(ctx context.Context, query *StudentQuery, nodes []*StuLog, init func(*StuLog), assign func(*StuLog, *Student)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int64]*StuLog)
	nids := make(map[int64]map[*StuLog]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(stulog.StudentsTable)
		s.Join(joinT).On(s.C(student.FieldID), joinT.C(stulog.StudentsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(stulog.StudentsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(stulog.StudentsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullInt64).Int64
				inValue := values[1].(*sql.NullInt64).Int64
				if nids[inValue] == nil {
					nids[inValue] = map[*StuLog]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Student](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "students" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *StuLogQuery) loadImages(ctx context.Context, query *ImageQuery, nodes []*StuLog, init func(*StuLog), assign func(*StuLog, *Image)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int64]*StuLog)
	nids := make(map[int64]map[*StuLog]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(stulog.ImagesTable)
		s.Join(joinT).On(s.C(image.FieldID), joinT.C(stulog.ImagesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(stulog.ImagesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(stulog.ImagesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullInt64).Int64
				inValue := values[1].(*sql.NullInt64).Int64
				if nids[inValue] == nil {
					nids[inValue] = map[*StuLog]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Image](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "images" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *StuLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *StuLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stulog.Table, stulog.Columns, sqlgraph.NewFieldSpec(stulog.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stulog.FieldID)
		for i := range fields {
			if fields[i] != stulog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *StuLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(stulog.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = stulog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StuLogGroupBy is the group-by builder for StuLog entities.
type StuLogGroupBy struct {
	selector
	build *StuLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *StuLogGroupBy) Aggregate(fns ...AggregateFunc) *StuLogGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *StuLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StuLogQuery, *StuLogGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *StuLogGroupBy) sqlScan(ctx context.Context, root *StuLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StuLogSelect is the builder for selecting fields of StuLog entities.
type StuLogSelect struct {
	*StuLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *StuLogSelect) Aggregate(fns ...AggregateFunc) *StuLogSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *StuLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StuLogQuery, *StuLogSelect](ctx, _s.StuLogQuery, _s, _s.inters, v)
}

func (_s *StuLogSelect) sqlScan(ctx context.Context, root *StuLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
