syntax = "proto3";

package api.base_info.v1;
import "google/api/annotations.proto";
option go_package = "eGZ-stu-log/api/base_info/v1;v1";
option java_multiple_files = true;
option java_package = "api.base_info.v1";

service Class {
	rpc CreateClass (CreateClassRequest) returns (CreateClassReply) {
		option (google.api.http) = {
			post: "/api/base_info/class/create",
			body: "*"
		};
	}
}

message CreateClassRequest {
	string className = 1;
	int64 gradeId = 2;
}
message CreateClassReply {
	string message = 1;
}