// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: base_info/v1/grade.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeName     string                 `protobuf:"bytes,1,opt,name=gradeName,proto3" json:"gradeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGradeRequest) Reset() {
	*x = CreateGradeRequest{}
	mi := &file_base_info_v1_grade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGradeRequest) ProtoMessage() {}

func (x *CreateGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_grade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGradeRequest.ProtoReflect.Descriptor instead.
func (*CreateGradeRequest) Descriptor() ([]byte, []int) {
	return file_base_info_v1_grade_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGradeRequest) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

type CreateGradeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGradeReply) Reset() {
	*x = CreateGradeReply{}
	mi := &file_base_info_v1_grade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGradeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGradeReply) ProtoMessage() {}

func (x *CreateGradeReply) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_grade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGradeReply.ProtoReflect.Descriptor instead.
func (*CreateGradeReply) Descriptor() ([]byte, []int) {
	return file_base_info_v1_grade_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGradeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_base_info_v1_grade_proto protoreflect.FileDescriptor

const file_base_info_v1_grade_proto_rawDesc = "" +
	"\n" +
	"\x18base_info/v1/grade.proto\x12\x10api.base_info.v1\x1a\x1cgoogle/api/annotations.proto\"2\n" +
	"\x12CreateGradeRequest\x12\x1c\n" +
	"\tgradeName\x18\x01 \x01(\tR\tgradeName\",\n" +
	"\x10CreateGradeReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x87\x01\n" +
	"\x05Grade\x12~\n" +
	"\vCreateGrade\x12$.api.base_info.v1.CreateGradeRequest\x1a\".api.base_info.v1.CreateGradeReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/base_info/grade/createB5\n" +
	"\x10api.base_info.v1P\x01Z\x1feGZ-stu-log/api/base_info/v1;v1b\x06proto3"

var (
	file_base_info_v1_grade_proto_rawDescOnce sync.Once
	file_base_info_v1_grade_proto_rawDescData []byte
)

func file_base_info_v1_grade_proto_rawDescGZIP() []byte {
	file_base_info_v1_grade_proto_rawDescOnce.Do(func() {
		file_base_info_v1_grade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_info_v1_grade_proto_rawDesc), len(file_base_info_v1_grade_proto_rawDesc)))
	})
	return file_base_info_v1_grade_proto_rawDescData
}

var file_base_info_v1_grade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_info_v1_grade_proto_goTypes = []any{
	(*CreateGradeRequest)(nil), // 0: api.base_info.v1.CreateGradeRequest
	(*CreateGradeReply)(nil),   // 1: api.base_info.v1.CreateGradeReply
}
var file_base_info_v1_grade_proto_depIdxs = []int32{
	0, // 0: api.base_info.v1.Grade.CreateGrade:input_type -> api.base_info.v1.CreateGradeRequest
	1, // 1: api.base_info.v1.Grade.CreateGrade:output_type -> api.base_info.v1.CreateGradeReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_info_v1_grade_proto_init() }
func file_base_info_v1_grade_proto_init() {
	if File_base_info_v1_grade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_info_v1_grade_proto_rawDesc), len(file_base_info_v1_grade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_info_v1_grade_proto_goTypes,
		DependencyIndexes: file_base_info_v1_grade_proto_depIdxs,
		MessageInfos:      file_base_info_v1_grade_proto_msgTypes,
	}.Build()
	File_base_info_v1_grade_proto = out.File
	file_base_info_v1_grade_proto_goTypes = nil
	file_base_info_v1_grade_proto_depIdxs = nil
}
