// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.0
// source: base_info/v1/grade.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGradeCreateGrade = "/api.base_info.v1.Grade/CreateGrade"

type GradeHTTPServer interface {
	CreateGrade(context.Context, *CreateGradeRequest) (*CreateGradeReply, error)
}

func RegisterGradeHTTPServer(s *http.Server, srv GradeHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/base_info/grade/create", _Grade_CreateGrade0_HTTP_Handler(srv))
}

func _Grade_CreateGrade0_HTTP_Handler(srv GradeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGradeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGradeCreateGrade)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGrade(ctx, req.(*CreateGradeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateGradeReply)
		return ctx.Result(200, reply)
	}
}

type GradeHTTPClient interface {
	CreateGrade(ctx context.Context, req *CreateGradeRequest, opts ...http.CallOption) (rsp *CreateGradeReply, err error)
}

type GradeHTTPClientImpl struct {
	cc *http.Client
}

func NewGradeHTTPClient(client *http.Client) GradeHTTPClient {
	return &GradeHTTPClientImpl{client}
}

func (c *GradeHTTPClientImpl) CreateGrade(ctx context.Context, in *CreateGradeRequest, opts ...http.CallOption) (*CreateGradeReply, error) {
	var out CreateGradeReply
	pattern := "/v1/base_info/grade/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGradeCreateGrade))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
