// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: base_info/v1/stu_log.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StuLog_ReportStuLog_FullMethodName  = "/api.base_info.v1.StuLog/ReportStuLog"
	StuLog_GetStuLog_FullMethodName     = "/api.base_info.v1.StuLog/GetStuLog"
	StuLog_GetStuLogList_FullMethodName = "/api.base_info.v1.StuLog/GetStuLogList"
	StuLog_ExportStuLog_FullMethodName  = "/api.base_info.v1.StuLog/ExportStuLog"
)

// StuLogClient is the client API for StuLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StuLogClient interface {
	ReportStuLog(ctx context.Context, in *ReportStuLogRequest, opts ...grpc.CallOption) (*ReportStuLogReply, error)
	GetStuLog(ctx context.Context, in *GetStuLogRequest, opts ...grpc.CallOption) (*StuLogItem, error)
	GetStuLogList(ctx context.Context, in *GetStuLogListRequest, opts ...grpc.CallOption) (*GetStuLogListReply, error)
	ExportStuLog(ctx context.Context, in *ExportStuLogRequest, opts ...grpc.CallOption) (*ExportStuLogReply, error)
}

type stuLogClient struct {
	cc grpc.ClientConnInterface
}

func NewStuLogClient(cc grpc.ClientConnInterface) StuLogClient {
	return &stuLogClient{cc}
}

func (c *stuLogClient) ReportStuLog(ctx context.Context, in *ReportStuLogRequest, opts ...grpc.CallOption) (*ReportStuLogReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStuLogReply)
	err := c.cc.Invoke(ctx, StuLog_ReportStuLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stuLogClient) GetStuLog(ctx context.Context, in *GetStuLogRequest, opts ...grpc.CallOption) (*StuLogItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StuLogItem)
	err := c.cc.Invoke(ctx, StuLog_GetStuLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stuLogClient) GetStuLogList(ctx context.Context, in *GetStuLogListRequest, opts ...grpc.CallOption) (*GetStuLogListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStuLogListReply)
	err := c.cc.Invoke(ctx, StuLog_GetStuLogList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stuLogClient) ExportStuLog(ctx context.Context, in *ExportStuLogRequest, opts ...grpc.CallOption) (*ExportStuLogReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportStuLogReply)
	err := c.cc.Invoke(ctx, StuLog_ExportStuLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StuLogServer is the server API for StuLog service.
// All implementations must embed UnimplementedStuLogServer
// for forward compatibility.
type StuLogServer interface {
	ReportStuLog(context.Context, *ReportStuLogRequest) (*ReportStuLogReply, error)
	GetStuLog(context.Context, *GetStuLogRequest) (*StuLogItem, error)
	GetStuLogList(context.Context, *GetStuLogListRequest) (*GetStuLogListReply, error)
	ExportStuLog(context.Context, *ExportStuLogRequest) (*ExportStuLogReply, error)
	mustEmbedUnimplementedStuLogServer()
}

// UnimplementedStuLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStuLogServer struct{}

func (UnimplementedStuLogServer) ReportStuLog(context.Context, *ReportStuLogRequest) (*ReportStuLogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStuLog not implemented")
}
func (UnimplementedStuLogServer) GetStuLog(context.Context, *GetStuLogRequest) (*StuLogItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStuLog not implemented")
}
func (UnimplementedStuLogServer) GetStuLogList(context.Context, *GetStuLogListRequest) (*GetStuLogListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStuLogList not implemented")
}
func (UnimplementedStuLogServer) ExportStuLog(context.Context, *ExportStuLogRequest) (*ExportStuLogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportStuLog not implemented")
}
func (UnimplementedStuLogServer) mustEmbedUnimplementedStuLogServer() {}
func (UnimplementedStuLogServer) testEmbeddedByValue()                {}

// UnsafeStuLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StuLogServer will
// result in compilation errors.
type UnsafeStuLogServer interface {
	mustEmbedUnimplementedStuLogServer()
}

func RegisterStuLogServer(s grpc.ServiceRegistrar, srv StuLogServer) {
	// If the following call pancis, it indicates UnimplementedStuLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StuLog_ServiceDesc, srv)
}

func _StuLog_ReportStuLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStuLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StuLogServer).ReportStuLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StuLog_ReportStuLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StuLogServer).ReportStuLog(ctx, req.(*ReportStuLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StuLog_GetStuLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStuLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StuLogServer).GetStuLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StuLog_GetStuLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StuLogServer).GetStuLog(ctx, req.(*GetStuLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StuLog_GetStuLogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStuLogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StuLogServer).GetStuLogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StuLog_GetStuLogList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StuLogServer).GetStuLogList(ctx, req.(*GetStuLogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StuLog_ExportStuLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportStuLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StuLogServer).ExportStuLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StuLog_ExportStuLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StuLogServer).ExportStuLog(ctx, req.(*ExportStuLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StuLog_ServiceDesc is the grpc.ServiceDesc for StuLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StuLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.base_info.v1.StuLog",
	HandlerType: (*StuLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStuLog",
			Handler:    _StuLog_ReportStuLog_Handler,
		},
		{
			MethodName: "GetStuLog",
			Handler:    _StuLog_GetStuLog_Handler,
		},
		{
			MethodName: "GetStuLogList",
			Handler:    _StuLog_GetStuLogList_Handler,
		},
		{
			MethodName: "ExportStuLog",
			Handler:    _StuLog_ExportStuLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base_info/v1/stu_log.proto",
}
