// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: base_info/v1/stu_log.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportStuLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentIds    []int64                `protobuf:"varint,1,rep,packed,name=studentIds,proto3" json:"studentIds,omitempty"`
	RuleId        int64                  `protobuf:"varint,2,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	GradeId       int64                  `protobuf:"varint,6,opt,name=gradeId,proto3" json:"gradeId,omitempty"`
	ImageIds      []int64                `protobuf:"varint,5,rep,packed,name=imageIds,proto3" json:"imageIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStuLogRequest) Reset() {
	*x = ReportStuLogRequest{}
	mi := &file_base_info_v1_stu_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStuLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStuLogRequest) ProtoMessage() {}

func (x *ReportStuLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_stu_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStuLogRequest.ProtoReflect.Descriptor instead.
func (*ReportStuLogRequest) Descriptor() ([]byte, []int) {
	return file_base_info_v1_stu_log_proto_rawDescGZIP(), []int{0}
}

func (x *ReportStuLogRequest) GetStudentIds() []int64 {
	if x != nil {
		return x.StudentIds
	}
	return nil
}

func (x *ReportStuLogRequest) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *ReportStuLogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReportStuLogRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReportStuLogRequest) GetGradeId() int64 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *ReportStuLogRequest) GetImageIds() []int64 {
	if x != nil {
		return x.ImageIds
	}
	return nil
}

type ReportStuLogReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStuLogReply) Reset() {
	*x = ReportStuLogReply{}
	mi := &file_base_info_v1_stu_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStuLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStuLogReply) ProtoMessage() {}

func (x *ReportStuLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_stu_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStuLogReply.ProtoReflect.Descriptor instead.
func (*ReportStuLogReply) Descriptor() ([]byte, []int) {
	return file_base_info_v1_stu_log_proto_rawDescGZIP(), []int{1}
}

func (x *ReportStuLogReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_base_info_v1_stu_log_proto protoreflect.FileDescriptor

const file_base_info_v1_stu_log_proto_rawDesc = "" +
	"\n" +
	"\x1abase_info/v1/stu_log.proto\x12\x10api.base_info.v1\x1a\x1cgoogle/api/annotations.proto\"\xb3\x01\n" +
	"\x13ReportStuLogRequest\x12\x1e\n" +
	"\n" +
	"studentIds\x18\x01 \x03(\x03R\n" +
	"studentIds\x12\x16\n" +
	"\x06ruleId\x18\x02 \x01(\x03R\x06ruleId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x18\n" +
	"\agradeId\x18\x06 \x01(\x03R\agradeId\x12\x1a\n" +
	"\bimageIds\x18\x05 \x03(\x03R\bimageIds\"-\n" +
	"\x11ReportStuLogReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x83\x01\n" +
	"\x06StuLog\x12y\n" +
	"\fReportStuLog\x12%.api.base_info.v1.ReportStuLogRequest\x1a#.api.base_info.v1.ReportStuLogReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/stu_log/reportB5\n" +
	"\x10api.base_info.v1P\x01Z\x1feGZ-stu-log/api/base_info/v1;v1b\x06proto3"

var (
	file_base_info_v1_stu_log_proto_rawDescOnce sync.Once
	file_base_info_v1_stu_log_proto_rawDescData []byte
)

func file_base_info_v1_stu_log_proto_rawDescGZIP() []byte {
	file_base_info_v1_stu_log_proto_rawDescOnce.Do(func() {
		file_base_info_v1_stu_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_info_v1_stu_log_proto_rawDesc), len(file_base_info_v1_stu_log_proto_rawDesc)))
	})
	return file_base_info_v1_stu_log_proto_rawDescData
}

var file_base_info_v1_stu_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_info_v1_stu_log_proto_goTypes = []any{
	(*ReportStuLogRequest)(nil), // 0: api.base_info.v1.ReportStuLogRequest
	(*ReportStuLogReply)(nil),   // 1: api.base_info.v1.ReportStuLogReply
}
var file_base_info_v1_stu_log_proto_depIdxs = []int32{
	0, // 0: api.base_info.v1.StuLog.ReportStuLog:input_type -> api.base_info.v1.ReportStuLogRequest
	1, // 1: api.base_info.v1.StuLog.ReportStuLog:output_type -> api.base_info.v1.ReportStuLogReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_info_v1_stu_log_proto_init() }
func file_base_info_v1_stu_log_proto_init() {
	if File_base_info_v1_stu_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_info_v1_stu_log_proto_rawDesc), len(file_base_info_v1_stu_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_info_v1_stu_log_proto_goTypes,
		DependencyIndexes: file_base_info_v1_stu_log_proto_depIdxs,
		MessageInfos:      file_base_info_v1_stu_log_proto_msgTypes,
	}.Build()
	File_base_info_v1_stu_log_proto = out.File
	file_base_info_v1_stu_log_proto_goTypes = nil
	file_base_info_v1_stu_log_proto_depIdxs = nil
}
