syntax = "proto3";

package api.base_info.v1;

import "google/api/annotations.proto";
option go_package = "eGZ-stu-log/api/base_info/v1;v1";
option java_multiple_files = true;
option java_package = "api.base_info.v1";
service StuLog {
	rpc ReportStuLog (ReportStuLogRequest) returns (ReportStuLogReply) {
		option (google.api.http) = {
			post: "/v1/stu_log/report",
			body: "*"
		};
	};
}

message ReportStuLogRequest {
	repeated int64 studentIds = 1;
	int64 ruleId = 2;
	string content = 3;
	int32 score = 4;
	int64 gradeId = 6;
	repeated int64 imageIds = 5;
}

message ReportStuLogReply {
	string message = 1;
}