// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: base_info/v1/stu_log.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StuLog_ReportStuLog_FullMethodName = "/api.base_info.v1.StuLog/ReportStuLog"
)

// StuLogClient is the client API for StuLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StuLogClient interface {
	ReportStuLog(ctx context.Context, in *ReportStuLogRequest, opts ...grpc.CallOption) (*ReportStuLogReply, error)
}

type stuLogClient struct {
	cc grpc.ClientConnInterface
}

func NewStuLogClient(cc grpc.ClientConnInterface) StuLogClient {
	return &stuLogClient{cc}
}

func (c *stuLogClient) ReportStuLog(ctx context.Context, in *ReportStuLogRequest, opts ...grpc.CallOption) (*ReportStuLogReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStuLogReply)
	err := c.cc.Invoke(ctx, StuLog_ReportStuLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StuLogServer is the server API for StuLog service.
// All implementations must embed UnimplementedStuLogServer
// for forward compatibility.
type StuLogServer interface {
	ReportStuLog(context.Context, *ReportStuLogRequest) (*ReportStuLogReply, error)
	mustEmbedUnimplementedStuLogServer()
}

// UnimplementedStuLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStuLogServer struct{}

func (UnimplementedStuLogServer) ReportStuLog(context.Context, *ReportStuLogRequest) (*ReportStuLogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStuLog not implemented")
}
func (UnimplementedStuLogServer) mustEmbedUnimplementedStuLogServer() {}
func (UnimplementedStuLogServer) testEmbeddedByValue()                {}

// UnsafeStuLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StuLogServer will
// result in compilation errors.
type UnsafeStuLogServer interface {
	mustEmbedUnimplementedStuLogServer()
}

func RegisterStuLogServer(s grpc.ServiceRegistrar, srv StuLogServer) {
	// If the following call pancis, it indicates UnimplementedStuLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StuLog_ServiceDesc, srv)
}

func _StuLog_ReportStuLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStuLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StuLogServer).ReportStuLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StuLog_ReportStuLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StuLogServer).ReportStuLog(ctx, req.(*ReportStuLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StuLog_ServiceDesc is the grpc.ServiceDesc for StuLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StuLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.base_info.v1.StuLog",
	HandlerType: (*StuLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStuLog",
			Handler:    _StuLog_ReportStuLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base_info/v1/stu_log.proto",
}
