syntax = "proto3";

package api.base_info.v1;

import "google/api/annotations.proto";
option go_package = "eGZ-stu-log/api/base_info/v1;v1";
option java_multiple_files = true;
option java_package = "api.base_info.v1";

message StuLogStudentItem  {
  int64 id = 1;
  string name = 2;
  string class = 4;
  string stuNum = 5;
}

message StuLogItem {
  int64 id = 1;
  repeated StuLogStudentItem students = 2;
  string rule = 3;
  string content = 4;
  int32 score = 5;
  string grade = 6;
  bool revoked = 8;
  string time = 9;
  string dormBuilding = 10;
  string dormNum = 11;
  repeated string imageUrls = 7;
}

service StuLog {
  rpc ReportStuLog (ReportStuLogRequest) returns (ReportStuLogReply) {
    option (google.api.http) = {
      post: "/v1/stu_log/report",
      body: "*"
    };
  };
  rpc GetStuLog (GetStuLogRequest) returns (StuLogItem) {
    option (google.api.http) = {
      get: "/v1/stu_log",
    };
  };
  rpc GetStuLogList (GetStuLogListRequest) returns (GetStuLogListReply) {
    option (google.api.http) = {
      get: "/v1/stu_log/list",
    };
  };
  rpc ExportStuLog (ExportStuLogRequest) returns (ExportStuLogReply) {
    option (google.api.http) = {
      get: "/v1/stu_log/export",
    };
  };
  rpc RevokeStuLog (RevokeStuLogRequest) returns (RevokeStuLogReply) {
    option (google.api.http) = {
      get: "/v1/stu_log/revoke",
    };
  };
  rpc GetRuleList (GetRuleRequest) returns (GetRuleReply) {
    option (google.api.http) = {
      get: "/v1/stu_log/rule",
    };
  };
  rpc GetDormList (GetDormRequest) returns (GetDormReply) {
    option (google.api.http) = {
      get: "/v1/stu_log/dorm",
    };
  };
}

message ReportStuLogRequest {
  repeated int64 studentIds = 1;
  int64 ruleId = 2;
  string content = 3;
  int32 score = 4;
  int64 gradeId = 6;
  optional int64 dormId = 7;
  repeated int64 imageIds = 5;
}

message ReportStuLogReply {
  string message = 1;
}

message GetStuLogRequest {
  int64 id = 1;
}

message GetStuLogListRequest {
  int64 page = 1;
  int64 pageSize = 2;
  optional int64 dormId = 8;
  optional int64 gradeId = 3;
  optional int64 ruleId = 4;
  optional int64 studentId = 5;
  optional int64 startTime = 6;
  optional int64 endTime = 7;
  optional bool onlyDorm = 9;
}

message GetStuLogListReply {
  repeated StuLogItem list = 1;
  int64 total = 2;
}

message ExportStuLogRequest {
  optional int64 gradeId = 3;
  optional int64 ruleId = 4;
  optional int64 studentId = 5;
  optional int64 startTime = 6;
  optional int64 endTime = 7;
}

message ExportStuLogReply {
  string exportPath = 1;
}

message RevokeStuLogRequest {
  int64 id = 1;
  bool revoke = 2;
}

message RevokeStuLogReply {
  string message = 1;
}

message RuleItem {
  string group = 1;
  string rule = 2;
  int32 score = 3;
  int64 id = 4;
}

message GetRuleRequest {
}

message GetRuleReply {
  repeated RuleItem list = 1;
}
message DormItem {
  string dormBuilding = 1;
  string dormNum = 2;
  string sex = 3;
  string gradeName = 4;
  int64 id = 5;
}
message GetDormRequest {

}

message GetDormReply {
  repeated DormItem list = 1;
}