// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: base_info/v1/student.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StuLogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Rule          string                 `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	Invoked       bool                   `protobuf:"varint,5,opt,name=invoked,proto3" json:"invoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StuLogItem) Reset() {
	*x = StuLogItem{}
	mi := &file_base_info_v1_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StuLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuLogItem) ProtoMessage() {}

func (x *StuLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuLogItem.ProtoReflect.Descriptor instead.
func (*StuLogItem) Descriptor() ([]byte, []int) {
	return file_base_info_v1_student_proto_rawDescGZIP(), []int{0}
}

func (x *StuLogItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StuLogItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StuLogItem) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *StuLogItem) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *StuLogItem) GetInvoked() bool {
	if x != nil {
		return x.Invoked
	}
	return false
}

type StudentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex           string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	StuNum        string                 `protobuf:"bytes,12,opt,name=stuNum,proto3" json:"stuNum,omitempty"`
	ClassId       int64                  `protobuf:"varint,4,opt,name=classId,proto3" json:"classId,omitempty"`
	ClassName     string                 `protobuf:"bytes,10,opt,name=className,proto3" json:"className,omitempty"`
	DormId        int64                  `protobuf:"varint,5,opt,name=dormId,proto3" json:"dormId,omitempty"`
	DormName      string                 `protobuf:"bytes,9,opt,name=dormName,proto3" json:"dormName,omitempty"`
	DormBuilding  string                 `protobuf:"bytes,11,opt,name=dormBuilding,proto3" json:"dormBuilding,omitempty"`
	GradeId       int64                  `protobuf:"varint,6,opt,name=gradeId,proto3" json:"gradeId,omitempty"`
	GradeName     string                 `protobuf:"bytes,8,opt,name=gradeName,proto3" json:"gradeName,omitempty"`
	DormPos       string                 `protobuf:"bytes,7,opt,name=dormPos,proto3" json:"dormPos,omitempty"`
	Score         int32                  `protobuf:"varint,13,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentItem) Reset() {
	*x = StudentItem{}
	mi := &file_base_info_v1_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentItem) ProtoMessage() {}

func (x *StudentItem) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentItem.ProtoReflect.Descriptor instead.
func (*StudentItem) Descriptor() ([]byte, []int) {
	return file_base_info_v1_student_proto_rawDescGZIP(), []int{1}
}

func (x *StudentItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentItem) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *StudentItem) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *StudentItem) GetClassId() int64 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *StudentItem) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *StudentItem) GetDormId() int64 {
	if x != nil {
		return x.DormId
	}
	return 0
}

func (x *StudentItem) GetDormName() string {
	if x != nil {
		return x.DormName
	}
	return ""
}

func (x *StudentItem) GetDormBuilding() string {
	if x != nil {
		return x.DormBuilding
	}
	return ""
}

func (x *StudentItem) GetGradeId() int64 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *StudentItem) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *StudentItem) GetDormPos() string {
	if x != nil {
		return x.DormPos
	}
	return ""
}

func (x *StudentItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CreateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex           string                 `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	ClassId       int64                  `protobuf:"varint,3,opt,name=classId,proto3" json:"classId,omitempty"`
	DormId        int64                  `protobuf:"varint,4,opt,name=dormId,proto3" json:"dormId,omitempty"`
	GradeId       int64                  `protobuf:"varint,5,opt,name=gradeId,proto3" json:"gradeId,omitempty"`
	DormPos       string                 `protobuf:"bytes,6,opt,name=dormPos,proto3" json:"dormPos,omitempty"`
	StuNum        string                 `protobuf:"bytes,7,opt,name=stuNum,proto3" json:"stuNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_base_info_v1_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_base_info_v1_student_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStudentRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *CreateStudentRequest) GetClassId() int64 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *CreateStudentRequest) GetDormId() int64 {
	if x != nil {
		return x.DormId
	}
	return 0
}

func (x *CreateStudentRequest) GetGradeId() int64 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *CreateStudentRequest) GetDormPos() string {
	if x != nil {
		return x.DormPos
	}
	return ""
}

func (x *CreateStudentRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

type CreateStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentReply) Reset() {
	*x = CreateStudentReply{}
	mi := &file_base_info_v1_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentReply) ProtoMessage() {}

func (x *CreateStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentReply.ProtoReflect.Descriptor instead.
func (*CreateStudentReply) Descriptor() ([]byte, []int) {
	return file_base_info_v1_student_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStudentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStudentRequest) Reset() {
	*x = QueryStudentRequest{}
	mi := &file_base_info_v1_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStudentRequest) ProtoMessage() {}

func (x *QueryStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStudentRequest.ProtoReflect.Descriptor instead.
func (*QueryStudentRequest) Descriptor() ([]byte, []int) {
	return file_base_info_v1_student_proto_rawDescGZIP(), []int{4}
}

func (x *QueryStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QueryStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentItem           `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStudentReply) Reset() {
	*x = QueryStudentReply{}
	mi := &file_base_info_v1_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStudentReply) ProtoMessage() {}

func (x *QueryStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStudentReply.ProtoReflect.Descriptor instead.
func (*QueryStudentReply) Descriptor() ([]byte, []int) {
	return file_base_info_v1_student_proto_rawDescGZIP(), []int{5}
}

func (x *QueryStudentReply) GetStudent() *StudentItem {
	if x != nil {
		return x.Student
	}
	return nil
}

type QueryStudentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	GradeId       *int64                 `protobuf:"varint,3,opt,name=gradeId,proto3,oneof" json:"gradeId,omitempty"`
	ClassId       *int64                 `protobuf:"varint,4,opt,name=classId,proto3,oneof" json:"classId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStudentListRequest) Reset() {
	*x = QueryStudentListRequest{}
	mi := &file_base_info_v1_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStudentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStudentListRequest) ProtoMessage() {}

func (x *QueryStudentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStudentListRequest.ProtoReflect.Descriptor instead.
func (*QueryStudentListRequest) Descriptor() ([]byte, []int) {
	return file_base_info_v1_student_proto_rawDescGZIP(), []int{6}
}

func (x *QueryStudentListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryStudentListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryStudentListRequest) GetGradeId() int64 {
	if x != nil && x.GradeId != nil {
		return *x.GradeId
	}
	return 0
}

func (x *QueryStudentListRequest) GetClassId() int64 {
	if x != nil && x.ClassId != nil {
		return *x.ClassId
	}
	return 0
}

type QueryStudentListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*StudentItem         `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStudentListReply) Reset() {
	*x = QueryStudentListReply{}
	mi := &file_base_info_v1_student_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStudentListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStudentListReply) ProtoMessage() {}

func (x *QueryStudentListReply) ProtoReflect() protoreflect.Message {
	mi := &file_base_info_v1_student_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStudentListReply.ProtoReflect.Descriptor instead.
func (*QueryStudentListReply) Descriptor() ([]byte, []int) {
	return file_base_info_v1_student_proto_rawDescGZIP(), []int{7}
}

func (x *QueryStudentListReply) GetStudents() []*StudentItem {
	if x != nil {
		return x.Students
	}
	return nil
}

func (x *QueryStudentListReply) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_base_info_v1_student_proto protoreflect.FileDescriptor

const file_base_info_v1_student_proto_rawDesc = "" +
	"\n" +
	"\x1abase_info/v1/student.proto\x12\x10api.base_info.v1\x1a\x1cgoogle/api/annotations.proto\"x\n" +
	"\n" +
	"StuLogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x12\n" +
	"\x04rule\x18\x04 \x01(\tR\x04rule\x12\x18\n" +
	"\ainvoked\x18\x05 \x01(\bR\ainvoked\"\xd3\x02\n" +
	"\vStudentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\tR\x03sex\x12\x16\n" +
	"\x06stuNum\x18\f \x01(\tR\x06stuNum\x12\x18\n" +
	"\aclassId\x18\x04 \x01(\x03R\aclassId\x12\x1c\n" +
	"\tclassName\x18\n" +
	" \x01(\tR\tclassName\x12\x16\n" +
	"\x06dormId\x18\x05 \x01(\x03R\x06dormId\x12\x1a\n" +
	"\bdormName\x18\t \x01(\tR\bdormName\x12\"\n" +
	"\fdormBuilding\x18\v \x01(\tR\fdormBuilding\x12\x18\n" +
	"\agradeId\x18\x06 \x01(\x03R\agradeId\x12\x1c\n" +
	"\tgradeName\x18\b \x01(\tR\tgradeName\x12\x18\n" +
	"\adormPos\x18\a \x01(\tR\adormPos\x12\x14\n" +
	"\x05score\x18\r \x01(\x05R\x05score\"\xba\x01\n" +
	"\x14CreateStudentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sex\x18\x02 \x01(\tR\x03sex\x12\x18\n" +
	"\aclassId\x18\x03 \x01(\x03R\aclassId\x12\x16\n" +
	"\x06dormId\x18\x04 \x01(\x03R\x06dormId\x12\x18\n" +
	"\agradeId\x18\x05 \x01(\x03R\agradeId\x12\x18\n" +
	"\adormPos\x18\x06 \x01(\tR\adormPos\x12\x16\n" +
	"\x06stuNum\x18\a \x01(\tR\x06stuNum\".\n" +
	"\x12CreateStudentReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x13QueryStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x11QueryStudentReply\x127\n" +
	"\astudent\x18\x01 \x01(\v2\x1d.api.base_info.v1.StudentItemR\astudent\"\x9f\x01\n" +
	"\x17QueryStudentListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\agradeId\x18\x03 \x01(\x03H\x00R\agradeId\x88\x01\x01\x12\x1d\n" +
	"\aclassId\x18\x04 \x01(\x03H\x01R\aclassId\x88\x01\x01B\n" +
	"\n" +
	"\b_gradeIdB\n" +
	"\n" +
	"\b_classId\"r\n" +
	"\x15QueryStudentListReply\x129\n" +
	"\bstudents\x18\x01 \x03(\v2\x1d.api.base_info.v1.StudentItemR\bstudents\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages2\x9a\x03\n" +
	"\aStudent\x12\x86\x01\n" +
	"\rCreateStudent\x12&.api.base_info.v1.CreateStudentRequest\x1a$.api.base_info.v1.CreateStudentReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/base_info/student/create\x12~\n" +
	"\fQueryStudent\x12%.api.base_info.v1.QueryStudentRequest\x1a#.api.base_info.v1.QueryStudentReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/base_info/student/{id}\x12\x85\x01\n" +
	"\x10QueryStudentList\x12).api.base_info.v1.QueryStudentListRequest\x1a'.api.base_info.v1.QueryStudentListReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/base_info/studentB5\n" +
	"\x10api.base_info.v1P\x01Z\x1feGZ-stu-log/api/base_info/v1;v1b\x06proto3"

var (
	file_base_info_v1_student_proto_rawDescOnce sync.Once
	file_base_info_v1_student_proto_rawDescData []byte
)

func file_base_info_v1_student_proto_rawDescGZIP() []byte {
	file_base_info_v1_student_proto_rawDescOnce.Do(func() {
		file_base_info_v1_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_info_v1_student_proto_rawDesc), len(file_base_info_v1_student_proto_rawDesc)))
	})
	return file_base_info_v1_student_proto_rawDescData
}

var file_base_info_v1_student_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_base_info_v1_student_proto_goTypes = []any{
	(*StuLogItem)(nil),              // 0: api.base_info.v1.StuLogItem
	(*StudentItem)(nil),             // 1: api.base_info.v1.StudentItem
	(*CreateStudentRequest)(nil),    // 2: api.base_info.v1.CreateStudentRequest
	(*CreateStudentReply)(nil),      // 3: api.base_info.v1.CreateStudentReply
	(*QueryStudentRequest)(nil),     // 4: api.base_info.v1.QueryStudentRequest
	(*QueryStudentReply)(nil),       // 5: api.base_info.v1.QueryStudentReply
	(*QueryStudentListRequest)(nil), // 6: api.base_info.v1.QueryStudentListRequest
	(*QueryStudentListReply)(nil),   // 7: api.base_info.v1.QueryStudentListReply
}
var file_base_info_v1_student_proto_depIdxs = []int32{
	1, // 0: api.base_info.v1.QueryStudentReply.student:type_name -> api.base_info.v1.StudentItem
	1, // 1: api.base_info.v1.QueryStudentListReply.students:type_name -> api.base_info.v1.StudentItem
	2, // 2: api.base_info.v1.Student.CreateStudent:input_type -> api.base_info.v1.CreateStudentRequest
	4, // 3: api.base_info.v1.Student.QueryStudent:input_type -> api.base_info.v1.QueryStudentRequest
	6, // 4: api.base_info.v1.Student.QueryStudentList:input_type -> api.base_info.v1.QueryStudentListRequest
	3, // 5: api.base_info.v1.Student.CreateStudent:output_type -> api.base_info.v1.CreateStudentReply
	5, // 6: api.base_info.v1.Student.QueryStudent:output_type -> api.base_info.v1.QueryStudentReply
	7, // 7: api.base_info.v1.Student.QueryStudentList:output_type -> api.base_info.v1.QueryStudentListReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_base_info_v1_student_proto_init() }
func file_base_info_v1_student_proto_init() {
	if File_base_info_v1_student_proto != nil {
		return
	}
	file_base_info_v1_student_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_info_v1_student_proto_rawDesc), len(file_base_info_v1_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_info_v1_student_proto_goTypes,
		DependencyIndexes: file_base_info_v1_student_proto_depIdxs,
		MessageInfos:      file_base_info_v1_student_proto_msgTypes,
	}.Build()
	File_base_info_v1_student_proto = out.File
	file_base_info_v1_student_proto_goTypes = nil
	file_base_info_v1_student_proto_depIdxs = nil
}
