syntax = "proto3";

package api.base_info.v1;

import "google/api/annotations.proto";
option go_package = "eGZ-stu-log/api/base_info/v1;v1";
option java_multiple_files = true;
option java_package = "api.base_info.v1";

service Student {
  // 学生创建
	rpc CreateStudent (CreateStudentRequest) returns (CreateStudentReply) {
    option (google.api.http) = {
      post: "v1/student/create",
      body: "*"
    };
  };
}

message CreateStudentRequest {
  string name = 1;
  string sex = 2;
  int32 classId = 3;
  int32 dormId = 4;
  int32 gradeId = 5;
}
message CreateStudentReply {
  string message = 1;
}
